"""empty message

Revision ID: 1422ac7b7fd6
Revises: f586b53120c5
Create Date: 2025-10-02 22:31:25.762771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1422ac7b7fd6'
down_revision = 'f586b53120c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adsgram_block_id', sa.String(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('adsgram_block_id')

    # ### end Alembic commands ###
