"""empty message

Revision ID: 52169cfa754e
Revises: e7e443a0f57d
Create Date: 2025-10-04 02:53:40.886662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52169cfa754e'
down_revision = 'e7e443a0f57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('rings',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=9),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('rings',
               existing_type=sa.Numeric(precision=20, scale=9),
               type_=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
