"""empty message

Revision ID: b22ad4435b1a
Revises: f54d3a90b0ba
Create Date: 2025-09-28 17:47:21.792297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22ad4435b1a'
down_revision = 'f54d3a90b0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('COMPLETED', 'PENDING', 'FAILED', 'PROCESSING', name='transactionstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('COMPLETED', 'PENDING', 'FAILED', 'PROCESSING', name='transactionstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
